name: demo_flutter_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  injectable: ^2.5.0
  go_router: ^14.8.0
  get_it: ^8.0.3
  fpdart: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
